### ISSUE TITLE
Any plans to add WebVR/WebXR support?

### ISSUE THREAD

**Issue by Sgeo** [magcius/noclip.website#106]
It would be incredible to see some of these levels in VR, especially without worrying about issues like frustum culling or getting real emulators to support VR.

**Comment by magcius** [comment]
I personally get very sick in VR headsets, but I welcome community contributions. Jawchewa started on something a while ago ( https://www.youtube.com/watch?v=Ajx8iAGBe78 ) which might be a starting point.

**Comment by Sgeo** [comment]
Do we know if that code is somewhere? Are there particular missing features, or might it be sufficient for public use? @jawchewa

**Comment by magcius** [comment]
https://github.com/jawchewa/noclip.website/tree/Experimental_VR

**Comment by jawchewa** [comment]
Yeah, the branch is incredibly behind, since I haven't really looked at this like 7-ish months ago. It would probably need to be updated, and their are likely a lot of merge conflicts that would need to be resolved. It's not really ready at all for public use, as it was mostly a proof of concept. From what I remember, the biggest issues that still existed were that the projection math wasn't quite setup properly so the effect didn't look quite right, and it was never quite hooked up to the existing movement and camera systems. There's probably a lot of other little stuff that would need to make it useable for public use.
