### ISSUE TITLE
Add support for Half-Life 1 (GoldSrc or source)

### ISSUE THREAD

**Issue by steren** [magcius/noclip.website#419]
Amazing website. 
I wish it also had Half Life 1 maps (either GoldSrc engine or Source)

https://github.com/skyrim/hlviewer.js is a viewer of GoldSrc maps that should be able to load and display the .bsp and .wad files.

**Comment by magcius** [comment]
Hi.

Due to overwhelming demand for lots of games to be added, I currently do not take on game requests from the public. If you wish to contribute code to add support for a game, I am happy to mentor people on the codebase and assist with writing game renderers. If that sounds interesting, please join the Discord messaged in the README, and I can help further.

Thanks.

**Comment by steren** [comment]
Looks like it was added as experimental: https://noclip.website/#HalfLife

Thanks!
