### ISSUE TITLE
Mario Kart 8 Deluxe: MacBookPro14,3 renders scenes as black and white

### ISSUE THREAD

**Issue by Tatsh** [magcius/noclip.website#458]
<img width="3008" alt="Mario Circuit - Mario Kart 8: Deluxe - noclip-2021-09-24 02-23-27" src="https://user-images.githubusercontent.com/724848/134628012-27651e7a-f8f5-4b26-b6ae-769a0b2e2293.png">

My nVidia systems do not have this issue. On this 2017 MacBook pro, only MK8DX shows like this. Other games work fine.

From system information:

```
Intel HD Graphics 630:
  Chipset Model:	Intel HD Graphics 630
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x591b
  Revision ID:	0x0004
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.29 [3.2.8]
  Metal Family:	Supported, Metal GPUFamily macOS 2

Radeon Pro 560:
  Chipset Model:	Radeon Pro 560
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	4 GB
  Vendor:	AMD (0x1002)
  Device ID:	0x67ef
  Revision ID:	0x00c0
  ROM Revision:	113-C980AJ-927
  VBIOS Version:	113-C9801AU-A02
  EFI Driver Version:	01.A0.927
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.29 [3.2.8]
  Metal Family:	Supported, Metal GPUFamily macOS 2

```

**Comment by magcius** [comment]
What version of Safari are you running?

**Comment by Tatsh** [comment]
This is with Chrome 95.0.4638.17.

I was actually able to get Mushroom Cup Mario Circuit to load textures once, but after that it went back to loading everything like in the screenshot above.

**Comment by magcius** [comment]
Could you try the latest Safari 15 Beta, or Firefox, and see if that works?

**Comment by Tatsh** [comment]
Got the same result in Firefox with a default installation.

In Safari Technology Preview 15.4 there's a WebGL exception. _WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost_

In Safari 15.0 it says 'A problem repeatedly occurred with ...' and gives me the option to reload.

**Comment by magcius** [comment]
I'm guessing that the system is running out of texture memory, possibly? You might be able to get a bit more info from the `chrome://gpu` status page.

**Comment by Tatsh** [comment]
The problem is to do with graphics switching in this MacBook Pro. Your site doesn't trigger a switch to the discrete. When I force discrete by disabling the switching in Battery settings, the site works consistently.

Would you consider putting `powerPreference: 'high-performance'` in the GL context? This should trigger use of the discrete GPU if available.

**Comment by magcius** [comment]
I'm not sure I'd want to do that for all games, but I don't believe I can change that after the fact.

**Comment by Tatsh** [comment]
Certainly games like Mario 64 DS don't need it. I've only had this issue with Mario Kart 8 since it's the newest and most detailed and I guess has the most textures to load at once. Even GTA San Andreas loads fine without needing to turn off GPU switching.

Another one that may benefit from 'high-performance' would be Diddy Kong Racing since it stresses the browser quite a bit when loading a level.

**Comment by magcius** [comment]
Yeah, my guess is that Mario Kart 8 blows out the texture memory of the smaller GPUs; the game normally ships BC1 textures, but they ship them sometimes with irregular sizes, which means I can't use the normal hardware compression path ( https://bugs.chromium.org/p/angleproject/issues/detail?id=6230 ), so it requires a lot of VRAM to show those levels.

I could possibly improve this by re-compressing textures into another format at load time, but that would be expensive (unless I preprocessed to use Basis or something)

For that reason, and because Mario Kart 8: Deluxe is in Experimental, I'm likely not going to switch the full site over to the high-performance mode. If I find a way of switching dynamically when switching games, I can investigate turning it on for Mario Kart 8: Deluxe only.
