### ISSUE TITLE
[Suggestion] Extra Source Engine render hacks

### ISSUE THREAD

**Issue by slambo311** [magcius/noclip.website#515]
I made a list of some Source Engine render hacks that could be used. I'm very experienced in the Source Engine, so the list is pretty long. I doubt ALL of them could be implemented, but ideas are ideas.

- Toggle 2D skyboxes
- Toggle 3D skyboxes (aka the sky projection stuff)
- Toggle Fullbright (mat_fullbright)
- Toggle Specular (mat_specular, makes stuff reflective)
- Toggle Phong (mat_phong, makes stuff shiny)
- Toggle Tool-only models (info_player_start's green guy, axes that Shesez mistook for something used to make the game, etc.)
- Picmip slider (mat_picmip, texture quality)
- LoD slider (r_lod, Level of Distance, model quality)
- Toggle NPC models
- Toggle projected textures/dynamic lights
- Toggle triggers entirely
- Activating triggers directly
- Worldportals (Most commonly seen in Portal 2 workshop levels, connecting the elevator rooms to the test chamber. Not to be confused with the portals actually shot by the portal gun)
- Toggle textures (maybe separate toggles for bump/normal maps?)
- Toggle water
- Toggle props (prop_static, prop_dynamic, prop_physics, all of that)
- Toggle other entities.

**Comment by magcius** [comment]
Some of these are supported as console commands, they just aren't exposed as a UI checkbox.

> Toggle 2D skyboxes

`main.scene.mainViewRenderer.drawSkybox2D = false`

> Toggle 3D skyboxes

`main.scene.mainViewRenderer.drawSkybox3D = false`

> Toggle Fullbright (mat_fullbright)

I have a local debug version of this, but I don't have it exposed on the site as a toggle -- it would require some surgery to implement, and to implement it for all material types.

> Toggle Specular (mat_specular, makes stuff reflective)
> Toggle Phong (mat_phong, makes stuff shiny)

I'd have to look at exactly how these work, but my material model doesn't quite match Source's -- Source has a number of base materials with different implementations (lightmappedgeneric, vertexlitgeneric, worldvertextransition, skin); I've unified them. There's no difference between "phong" and "specular" for me.

> Toggle Tool-only models (info_player_start's green guy, axes that Shesez mistook for something used to make the game, etc.)

These only have models in Hammer -- they aren't baked into the map at all.

> Picmip slider (mat_picmip, texture quality)

Would be difficult to do -- would require reuploading all textures. I don't see the point.

> LoD slider (r_lod, Level of Distance, model quality)

I render all models at max LOD right now. Perhaps it makes sense if we're bound by geometry/fillrate/quad occupancy eventually, but I believe everything is CPU/draw call limited, so I haven't really done much with that.

> Toggle NPC models

This would require determining which entities are NPCs -- whether the entity class name starts with `npc_` might be a good heuristic, but it's not perfect.

> Toggle projected textures/dynamic lights

`main.scene.mainViewRenderer.drawProjectedShadows = false`

> Toggle triggers entirely
> Activating triggers directly

More options for proper trigger usage is a good idea; I'll do it shortly.

> Worldportals (Most commonly seen in Portal 2 workshop levels, connecting the elevator rooms to the test chamber. Not to be confused with the portals actually shot by the portal gun)

This is a full feature request, and out of scope for this bug.

> Toggle textures (maybe separate toggles for bump/normal maps?)

Not sure how this would be different from mat_fullbright.

> Toggle water

`main.scene.mainViewRenderer.drawIndirect = false`

This will Refract surfaces as well as water; if you need something finer-grained I can do that, but hopefully this is enough for casual interest.

> Toggle props (prop_static, prop_dynamic, prop_physics, all of that)

prop_static are special because they get baked into a special part of the lump. You can turn them off with:

`main.scene.mainViewRenderer.renderObjectMask = 11;`

To hide only entities, use `13`. To hide both entities and static props, use `9`.

I should make this a nicer system in the future -- the original purpose was to hide certain kinds of objects from water reflection views.

> Toggle other entities.

What are "other entities"?

**Comment by slambo311** [comment]
> > Toggle textures (maybe separate toggles for bump/normal maps?)
> 
> Not sure how this would be different from mat_fullbright.

Fullbright disables lighting while disabling textures just make textures completely white, keeping lighting intact.

> > Toggle other entities.
> 
> What are "other entities"?

Basically, everything other than NPCs, props, and brushes, such as cyclers (like the pre-ep2 advisors on monitors), generic actors (like Lamarr), and doors (both `func_door_rotating`s and `func_door`s).

**Comment by slambo311** [comment]
Just realized how bad that fullbright explanation was. In the source engine, fullbright is basically the same thing as when you turn vertex colors off in other games.
