### ISSUE TITLE
Clapboard in Studio Mode does not hide the UI or give 2 second count-down

### ISSUE THREAD

**Issue by skdursh** [magcius/noclip.website#679]
I made a little relaxing looping animation for personal use as a desktop background, but can't seem to get the UI elements to go away when I attempt to record it. I read through the instructions and it says pressing the clapboard should hide all UI elements, but that isn't happening. It also doesn't give me the stated 2-second count down and instead begins the animation immediately. I'm not sure what the problem there is, but might there be a hotkey or other setting which can manually hide all of the UI elements? I looked but could not find anything in the instructions.

- Using Ungoogled-Chromium v125.0.6422.141-1 (Ungoogled-Chromium is essentially the exact same browser as standard Chromium, but with all of Google's tracking and statistical elements removed. It otherwise behaves the same as the mirror version of Chromium/Chrome)
- Enabled extensions include uBlockOrigin, Tampermonkey (but with no scripts running on noclip.website), Dark Reader, DecentralEyes, Reader View and Return Youtube Dislike, but as far as I can tell none of them seem to be interacting with noclip.website directly and even with all extensions disabled the issue persists.

**Comment by magcius** [comment]
When Studio mode detects WebCodecs, it changes the functionality of the record button with one that records and exports a video file directly -- when the animation is finished playing, a video file should be downloaded automatically. UI elements should not be captured in the video, so hiding them is not necessary.

Without WebCodecs, it puts a timer and hides UI elements so that you can record it using external capture software.

I suppose I need to update the documentation to reflect that.
